#!/bin/bash

state=$(bluetoothctl show | grep "Powered" )

if [[ "$state" == *"no"* ]]; then
  turn_on=$(bluetoothctl power on)
  filter=$(echo "$turn_on" | grep -oP "Changing power on succeeded")

  if [[ "$filter" == "Changing power on succeeded" ]]; then 
    notify-send -e -t 500 "Bluetooth" "Turned on"
  else 
    notify-send -e -u critical -t 500 "Bluetooth" "Failed to power on:\n$turn_on"
    exit
  fi

fi


device_list=$(bluetoothctl devices Paired) 
connected=$(bluetoothctl devices Connected) 
connectable="$device_list"


readarray -t array <<< "$connected"
for element in "${array[@]}"; do
  connectable="${connectable//$element/}"
done


connectable=$(echo -e "$connectable" | grep -v '^$')
device_names=$(echo "$connectable" | cut -d ' ' -f 3-)
selection=$(echo -e "$device_names" | $bluetooth_menu)

if [[ "$selection" == "" ]]; then 
  exit
fi

mac=$(echo "$connectable" | grep "$selection" | awk '{print $2}')
result=$(bluetoothctl connect "$mac")
result_check=$(echo "$result" | grep -oP "Connection successful|Failed to connect")

if [[ "$result_check" == "Failed to connect" ]]; then
  notify-send -e -u critical -t 500 "Bluetooth" "Failed to connect:\n$result"
  exit
fi


