#!/bin/bash

launcher="rofi"
class="Rofi"
cmd="rofi -dmenu -n -config /home/rom/.config/rofi/bluetooth.rasi -matching prefix -i "


# if pgrep -x "$launcher" > /dev/null; then 
#   pkill -x "$launcher"
# fi

# pgrep -x "$launcher" > /dev/null && pkill -x "$launcher"

$HOME/.config/hypr/scripts/smart_launch_menu.bash $launcher $class 

choice=$(eval "echo -e 'Connect\nDisconnect\nList\nPair\nForget\nTurn On\nKill\nRestart' | $cmd " )




# echo "choice: $choice"

[[ "$choice" == "" ]] && echo "cancelled" && exit


if [[ "$choice" == "Connect" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_connect
elif [[ "$choice" == "Disconnect" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_disconnect
elif [[ "$choice" == "Pair" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_pair
elif [[ "$choice" == "Forget" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_remove
elif [[ "$choice" == "Kill" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_off
elif [[ "$choice" == "List" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_list_connected
elif [[ "$choice" == "Turn On" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_on
elif [[ "$choice" == "Restart" ]]; then
  ~/.config/i3/dmenu_scripts/bluetooth_on
fi
echo "$choice"
