#!/bin/bash
connected=$(bluetoothctl devices Connected) 
device_names=$(echo "$connected" | cut -d ' ' -f 3-)
selection=$(echo -e "$device_names" | $bluetooth_menu)

if [[ "$selection" == "" ]]; then 
  exit
fi

mac=$(echo "$connected" | grep "$selection" | awk '{print $2}')
result=$(bluetoothctl disconnect "$mac")
result_check=$(echo "$result" | grep -oP "Successful disconnected")


if [[ "$result_check" != "Successful disconnected" ]]; then
  notify-send -e -u critical -t 500 "Bluetooth" "Failed to disconnect:\n$result"
  exit
fi


