#!/bin/bash

cmd="rofi -dmenu -n -config /home/rom/.config/rofi/bluetooth.rasi -matching prefix -i -steal-focus -normal-window"


pkill rofi

choice=$(eval "echo -e 'Connect\nDisconnect\nList\nPair\nForget\nBoot\nKill\nRestart' | $bluetooth_menu " )


[[ "$choice" == "" ]] && echo "cancelled" && exit


if [[ "$choice" == "Connect" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_connect
elif [[ "$choice" == "Disconnect" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_disconnect
elif [[ "$choice" == "Pair" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_pair
elif [[ "$choice" == "Forget" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_remove
elif [[ "$choice" == "Kill" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_off
elif [[ "$choice" == "List" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_list_connected
elif [[ "$choice" == "Boot" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_on
elif [[ "$choice" == "Restart" ]]; then
  ~/.config/menu_scripts/bluetooth/bluetooth_restart
fi

echo "$choice"
